services:
    directus:
        image: directus/directus:11.5.1
        ports:
            - 8055:8055
        volumes:
            - ./database:/directus/database
            - ./uploads:/directus/uploads
            - ./extensions:/directus/extensions
        environment:
            SECRET: "gnV4DRPSvx5WyYOX1wElk7"
            ADMIN_EMAIL: "admin@example.com"
            ADMIN_PASSWORD: "vQj59u970V2k"
            DB_CLIENT: "sqlite3"
            DB_FILENAME: "/directus/database/data.db"
            WEBSOCKETS_ENABLED: "true"
